#!/usr/bin/perl -w

use strict;
use MGA::Advisories;

my %advdb;
$advdb{advisories} = MGA::Advisories::get_advisories();
MGA::Advisories::publish_advisories(\%advdb);
MGA::Advisories::sort_advisories(\%advdb);
MGA::Advisories::output_pages(\%advdb);
MGA::Advisories::dumpdb(\%advdb);
MGA::Advisories::send_adv_mail(\%advdb);
MGA::Advisories::send_report_mail(\%advdb);

